server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 4511012
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
